spring:
  application:
    name: finger-nft-api
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 100MB
  messages:
    encoding: UTF-8
  mvc:
    async:
      request-timeout: 20000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/finger_nft?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: li123456
    hikari:
      minimum-idle: 6
      maximum-pool-size: 60
      pool-name: api-p
      max-lifetime: 60000
      connection-timeout: 60000

server:
  port: 10006
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 8000
    threads:
      max: 800
      min-spare: 100

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

logging:
  file:
    name: ${spring.application.name}
    path: logs
  level:
    org.springframework: info
    com.fingerchar.api: info

# biz config
com:
  finger:
    token-secret: Finger-Nft-Token
    cors-max-age: 30d

